/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "ksmの使用文档",
  "tagline": "让群里面多一只可爱的KsmBot吧",
  "favicon": "img/ksm.ico",
  "url": "https://ksmbot.github.io",
  "baseUrl": "/",
  "organizationName": "ksmbot",
  "projectName": "ksmbot.github.io",
  "deploymentBranch": "gh-pages",
  "trailingSlash": false,
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "i18n": {
    "defaultLocale": "zh-Hans",
    "locales": [
      "zh-Hans"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "E:\\ksmbot.github.io\\sidebars.js"
        },
        "theme": {
          "customCss": "E:\\ksmbot.github.io\\src\\css\\custom.css"
        }
      }
    ]
  ],
  "themeConfig": {
    "image": "img/title.jpg",
    "navbar": {
      "title": "ksmの使用文档",
      "logo": {
        "alt": "My Site Logo",
        "src": "img/ksm.ico"
      },
      "items": [
        {
          "type": "docSidebar",
          "sidebarId": "tutorialSidebar",
          "position": "left",
          "label": "ksm"
        },
        {
          "href": "https://github.com/ksmbot",
          "label": "GitHub",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "light",
      "links": [
        {
          "title": "Docs",
          "items": [
            {
              "label": "开始·加群须知",
              "to": "/docs/intro"
            },
            {
              "label": "使用说明",
              "to": "/docs/help"
            },
            {
              "label": "版权声明",
              "to": "/docs/CopyrightNotice"
            }
          ]
        },
        {
          "title": "友情链接",
          "items": [
            {
              "label": "户山兔兔的哔哩哔哩主页",
              "href": "https://b23.tv/U09RKL6"
            },
            {
              "label": "ksmbot的哔哩哔哩主页",
              "href": "https://b23.tv/RqRNoYl"
            },
            {
              "label": "小小趴bot by Kumo",
              "href": "http://xiaoxiaopa.com"
            },
            {
              "label": "另一只可爱的Kasumi Bot by 吉太",
              "href": "https://www.bilibili.com/read/cv20718127"
            },
            {
              "label": "KanonBot",
              "href": "https://www.bilibili.com/read/cv21464391"
            }
          ]
        },
        {
          "title": "更多",
          "items": [
            {
              "label": "我们的QQ群-欣遇庭",
              "href": "http://qm.qq.com/cgi-bin/qm/qr?_wv=1027&k=Lqal0PCVCKBlG22gu-9soLlaRqffOpJA&authKey=Gh%2BoZD%2FWg2t8%2BT0jAkmQ7QLQblOHNw%2FSr5tQwoka5I55JW94TzFqNPdm7kM4gJUC&noverify=0&group_code=737704963"
            },
            {
              "label": "基于ksm服务器的MinecraftPE服务器",
              "href": "/docs/mc"
            },
            {
              "label": "GitHub文档站项目（欢迎前来改错）",
              "href": "https://github.com/ksmBot/ksmbot.github.io"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2023 <a href=\"https://b23.tv/U09RKL6\">户山兔兔</a>"
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "mermaid": false
  }
};
